agent:
  parameters:
    markdown: false
knowledge:
  pdf:
    chunk: true
    chunk_overlap: 200
    chunk_size: 1000
    enabled: true
    path: data/pdfs
    table_name: pdf_documents
pgvector:
  container_name: pgvector
  db_name: ai
  db_password: ai
  db_user: ai
  host: localhost
  port: 5532
providers:
  anthropic:
    api_key_env: ANTHROPIC_API_KEY
    class: Claude
    enabled: false
    models:
    - display_name: Claude 3.7 Sonnet
      enabled: true
      name: claude-3-7-sonnet-20250219
      parameters:
        max_tokens: 1024
        temperature: 0.7
    module: agno.models.anthropic
  deepseek:
    api_key_env: DEEPSEEK_API_KEY
    class: DeepSeek
    enabled: false
    models:
    - display_name: DeepSeek Chat
      enabled: true
      name: deepseek-chat
      parameters:
        max_tokens: 1024
        temperature: 0.7
    module: agno.models.deepseek
  google:
    api_key_env: GOOGLE_API_KEY
    class: Gemini
    enabled: true
    models:
    - display_name: Gemini 2.0 Flash
      enabled: true
      max_tokens: 1024
      name: gemini-2.0-flash
      parameters:
        max_output_tokens: 1024
        temperature: 0.7
      temperature: 0.7
    - display_name: Gemini 2.5 Pro
      enabled: false
      name: gemini-2.5-pro-exp-03-25
      parameters:
        max_output_tokens: 1024
        temperature: 0.7
    module: agno.models.google
  groq:
    api_key_env: GROQ_API_KEY
    class: Groq
    enabled: false
    models:
    - display_name: Meta Llama 4 Scout 17B
      enabled: true
      name: meta-llama/llama-4-scout-17b-16e-instruct
      parameters:
        max_tokens: 1024
        temperature: 0.7
    - display_name: Alibaba Qwen 2.5 32B
      enabled: true
      name: qwen-2.5-32b
      parameters:
        max_tokens: 1024
        temperature: 0.7
    - display_name: Alibaba Qwen 2.5 Coder 32B
      enabled: false
      name: qwen-2.5-coder-32b
      parameters:
        max_tokens: 1024
        temperature: 0.7
    - display_name: DeepSeek R1 Distill Llama 70B
      enabled: true
      name: deepseek-r1-distill-llama-70b
      parameters:
        max_tokens: 1024
        temperature: 0.7
    - display_name: Mistral Saba 24B
      enabled: true
      name: mistral-saba-24b
      parameters:
        max_tokens: 1024
        temperature: 0.7
    module: agno.models.groq
  ibm:
    api_key_env: IBM_WATSONX_API_KEY
    class: WatsonX
    enabled: false
    models:
    - display_name: Granite 3.1 8B Instruct
      enabled: true
      name: ibm-granite/granite-3.1-8b-instruct
      parameters:
        max_tokens: 1024
        temperature: 0.7
    module: agno.models.ibm
  openai:
    api_key_env: OPENAI_API_KEY
    class: OpenAIChat
    enabled: true
    models:
    - display_name: GPT-4o Mini
      enabled: true
      name: gpt-4o-mini
      parameters:
        max_tokens: 1024
        temperature: 0.7
    module: agno.models.openai
  perplexity:
    api_key_env: PERPLEXITY_API_KEY
    class: Perplexity
    enabled: false
    models:
    - display_name: Sonar Pro
      enabled: true
      name: sonar-pro
      parameters:
        max_tokens: 1024
        temperature: 0.7
    - display_name: Sonar
      enabled: true
      name: sonar
      parameters:
        max_tokens: 1024
        temperature: 0.7
    module: agno.models.perplexity
  sambanova:
    api_key_env: SAMBANOVA_API_KEY
    class: Sambanova
    enabled: false
    models:
    - display_name: DeepSeek R1
      enabled: true
      name: DeepSeek-R1
      parameters:
        max_tokens: 1024
        temperature: 0.7
    - display_name: DeepSeek V3
      enabled: true
      name: DeepSeek-V3-0324
      parameters:
        max_tokens: 1024
        temperature: 0.7
    module: agno.models.sambanova
  together:
    api_key_env: TOGETHER_API_KEY
    class: Together
    enabled: false
    models:
    - display_name: Meta Llama 4 Maverick 17B
      enabled: true
      name: meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8
      parameters:
        max_tokens: 1024
        temperature: 0.7
    - display_name: Meta Llama 4 Scout 17B
      enabled: true
      name: meta-llama/Llama-4-Scout-17B-16E-Instruct
      parameters:
        max_tokens: 1024
        temperature: 0.7
    module: agno.models.together
  xai:
    api_key_env: XAI_API_KEY
    class: xAI
    enabled: false
    models:
    - display_name: Grok 2
      enabled: true
      name: grok-2-1212
      parameters:
        max_tokens: 1024
        temperature: 0.7
    module: agno.models.xai
ui:
  max_chat_history: 10
  models_per_row: 2
